name: Translate Documentation

on:
  schedule:
    - cron: '0 20 * * *' # Daily at 20:00 UTC (within DeepSeek API off-peak pricing window 16:30-00:30 UTC)
  workflow_dispatch: # Allow manual triggering

jobs:
  check_existing_branch:
    runs-on: ubuntu-latest
    outputs:
      branch_exists: ${{ steps.check_branch.outputs.exists }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check if docs/update-translations branch already exists
        id: check_branch
        run: |
          if git ls-remote --heads origin docs/update-translations | grep -q docs/update-translations; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi
        shell: bash

  translate:
    needs: check_existing_branch
    if: ${{ needs.check_existing_branch.outputs.branch_exists == 'false' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Run translation directly with npx
        run: npx @tanstack-dev/translate-docs
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        env:
          token: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit-message: 'docs: update documentation translations'
          title: 'Update translations'
          body: |
            This PR updates the documentation translations automatically.

            Generated by the translate workflow.
          branch: docs/update-translations
          delete-branch: true
          base: main
